default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root   # tu usuario de Postgres
  password: qwer1234           # tu contraseña, si tienes
  host: localhost
  port: 5432

development:
  <<: *default
  database: app_dev

test:
  <<: *default
  database: app_test

# Producción: PostgreSQL (todas las conexiones a la misma URL)
production:
  primary:
    url: <%= ENV["DATABASE_URL"] %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

  cache:
    url: <%= ENV["DATABASE_URL"] %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
    migrations_paths: db/cache_migrate

  queue:
    url: <%= ENV["DATABASE_URL"] %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
    migrations_paths: db/queue_migrate

  cable:
    url: <%= ENV["DATABASE_URL"] %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
    migrations_paths: db/cable_migrate
